import { Volkhov, Mulish, Rubik, Poppins, } from "next/font/google";
import "./globals.css";

// const mulish = Mulish({
//   variable: "--font-mulish",
//   subsets: ["latin"],
// });

// const volkhov = Volkhov({
//   variable: "--font-volkhov",
//   weight: ['400', '700'],
//   subsets: ["latin"],
// });

// default font family: Rubik
const rubik = Rubik({
  variable: "--font-rubik",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${rubik.className} ${poppins.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
